spring.application.name=learn-spring-ai

spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.chat.temperature=0.45
#spring.ai.ollama.embedding.model=embeddinggemma
#spring.ai.ollama.embedding.truncate=true
#spring.ai.ollama.embedding.keep-alive=5m

spring.ai.retry.max-attempts=2

# chat history db
spring.datasource.url=jdbc:postgresql://localhost:5432/learnspringai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.ai.chat.memory.repository.jdbc.initialize-schema=always