spring.application.name=learn-spring-ai

#spring.ai.model.chat=ollama
#spring.ai.model.embedding=ollama

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=llama3.2
#spring.ai.ollama.chat.model=gemma3:4b
#spring.ai.ollama.chat.temperature=0.45

#spring.ai.ollama.embedding.model=embeddinggemma
#spring.ai.ollama.embedding.truncate=true
#spring.ai.ollama.embedding.keep-alive=5m

spring.ai.retry.max-attempts=2

# chat history db
spring.datasource.url=jdbc:postgresql://localhost:5432/learnspringai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.ai.chat.memory.repository.jdbc.initialize-schema=always




# using google llm
# 1. Switch the model types to Google GenAI
spring.ai.model.chat=google-genai
spring.ai.model.embedding=google-genai

# 2. Add Google GenAI configurations
spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.image.model=gemini-3.1-flash-lite-image
spring.ai.google.genai.embedding.text.model=text-embedding-004